applications/urls.py
from django.urls import path
from . import views

# Djangoテンプレートで使用するためにURLルーティングの名前を付けておく
app_name='app_urls'

urlpatterns = [
	# トップページでは「applications/views.py」のindex関数を実行する
	# path('',views.index,name='index'),

	# dl_csv_zip系
	# URL「~/dl_csv_zip/」にアクセスした際に「applications/views.py」のdl_csv_zip関数を実行させる
	path('dl_csv_zip/',views.dl_csv_zip,name='dl_csv_zip'),
	# URL「~/dl_csv_zip_proc/」にアクセスした際に「applications/views.py」のdl_csv_zip_proc関数を実行させる
	path('dl_csv_zip_proc/',views.dl_csv_zip_proc,name='dl_csv_zip_proc'),

	# rec_ajax系
	# URL「~/rec_ajax/」にアクセスした際に「applications/views.py」のrec_ajax関数を実行させる
	path('rec_ajax/',views.rec_ajax,name='rec_ajax'),
	# Ajax経由でURL「~/rec_ajax_proc/」にアクセスした際に「applications/views.py」のrec_ajax_proc関数を実行させる
	# 「name='rec_ajax_proc'」は後ほどrec_ajax.htmlで使用する
	path('rec_ajax_proc/',views.rec_ajax_proc,name='rec_ajax_proc'),

	# ヘルプボタン系
	# URL「~/help_modal/」にアクセスした際に「applications/views.py」のhelp_modal関数を実行させる
	path('help_modal/',views.help_modal,name='help_modal'),
]

config/urls.py
from django.urls import include,path
from django.contrib import admin
from applications.views import frontpage


urlpatterns = [
	# トップページへのURLルーティングをapplicationsフォルダ内のurls.pyへ回す
	# path('',include('applications.urls')),

	path('', frontpage),

	# adminページの表示
	path('admin/', admin.site.urls,name='admin'),
	# ログイン関連ページの表示
	path('accounts/',include('django.contrib.auth.urls')),
]

applications/forms.py
from django import forms

class ScrapingForm(forms.Form):
    occupation = forms.CharField(max_length=255, widget=forms.Textarea)
    count = forms.IntegerField()

class SiteForm(forms.Form):
    site = forms.fields.ChoiceField(
        choices = (
            ('green', 'Green'),
            ('recnavi', 'リクナビ'),
            ('geekly', 'ギークリー')
        ),
        required=True,
        widget=forms.widgets.Select
    )

applications/views.py
import csv
import math
import time
import urllib.parse
import zipfile
from io import BytesIO
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse

from .forms import ScrapingForm, SiteForm
from .scraping import green, recruit, geekly


def frontpage(request):
	# POSTされていたらそのデータを表示
	conclusion = ""
	count = ""
	if request.method == "POST":
		form = ScrapingForm(request.POST)
		siteform = SiteForm(request.POST)
		if form.is_valid() & siteform.is_valid():
			count = form.cleaned_data['count']
			occupation = form.cleaned_data['occupation']
			site = siteform.cleaned_data['site']
			if site == "green":
				item_info = green(occupation, count)
				conclusion = f"成功しました。件数は{len(item_info)}です。"
			elif site == "recnavi":
				item_info = recruit(occupation, count)
				conclusion = f"成功しました。件数は{len(item_info)}です。"
			elif site == "geekly":
				item_info = geekly(occupation, count)
				conclusion = f"成功しました。件数は{len(item_info)}です。"
			else:
				conclusion = "エラーです。"
	else:
		form = ScrapingForm()
		siteform = SiteForm()
		count = ""
		conclusion = ""
		item_info=""
	return render(
		request,
		"frontpage.html",
		{
			"conclusion": conclusion,
			"form": form,
			"siteform": siteform,
			"count": count,
			"item_info":item_info,
		}
	)

# リンクページの表示
def index_bk(request):
	# ログインの確認
	if request.user.is_authenticated:
		return render(request,'applications/index.html')
	else:
		# ログインしていない場合はログインページへ移動
		return HttpResponseRedirect('/accounts/login/')
def index(request):
	return render(request,'applications/index.html')

# csvをzipでダウンロードするページの表示
def dl_csv_zip(request):
	# ログインの確認
	if request.user.is_authenticated:
		return render(request,'applications/dl_csv_zip.html')
	else:
		# ログインしていない場合はログインページへ移動
		return HttpResponseRedirect('/accounts/login/')


# 指定された辞書型リストをcsvに変換してzipでダウンロードする処理
def dl_csv_zip_proc(request):

	if request.method=='POST':
		# postされたcheckboxの内容をリストに格納
		checkbox_list=request.POST.getlist('checkbox')
		# actionがsaveかつ、checkbox_listが空でない場合
		# checkbox_listが空の場合に実行すると「zip」ファイルがダウンロードされてしまうのを防ぐ
		if request.POST.get('action')=='save' and checkbox_list:

			# 書き込むzipの準備
			memory_file=BytesIO()
			zip_file=zipfile.ZipFile(memory_file,'w')

			for item in checkbox_list:
				# csvの準備
				csv_file=HttpResponse(content_type='text/csv')
				# csvヘッダーの書き込み
				writer=csv.DictWriter(csv_file,['ts','chat'])
				writer.writeheader()
				# csvへの書き込み
				# postされたtextareaの内容は文字列のためevalで辞書型リストに変換
				writer.writerows(eval(request.POST.get(item)))
				# zipに圧縮
				zip_file.writestr(f'{item}.csv',csv_file.getvalue())
				csv_file.close()

			# zipの内容をreponseに設定
			#ここでcloseしないとエラーが発生して解凍できない
			zip_file.close()
			response=HttpResponse(memory_file.getvalue(), content_type='application/zip')
			# checkbox_listを「,」で区切ってURLエンコード
			quoted_filename = urllib.parse.quote(",".join(checkbox_list))
			# quoted_filenameをファイル名にする
			# filename*にURLエンコードしたファイル名をセットすることで日本語のファイル名にも対応可能
			response['Content-Disposition']=f'attachment; filename="{quoted_filename}.zip"; filename*=UTF-8"{quoted_filename}.zip"'

			# responseを返す
			return response

		# checkbox_listが空の場合は何もしないのでstatus=204を返す
		else:
			return HttpResponse(status=204)


# rec_ajaxページの表示
def rec_ajax(request):
	# ログインの確認
	if request.user.is_authenticated:
		return render(request,'applications/rec_ajax.html')
	else:
		# ログインしていない場合はログインページへ移動
		return HttpResponseRedirect('/accounts/login/')


# rec_ajaxの処理
def rec_ajax_proc(request):

	if request.method=='POST':
		# 進捗を計算するためにint型に変換
		select_num=int(request.POST.get('select_num'))

		# 1回目はnext_numがないため、tryで処理を分ける
		try:
			# postデータから取得し、進捗を計算するためにint型に変換
			current_num=int(request.POST.get('next_num'))
		except:
			# postデータからは取得できないため初期値を定義する
			current_num=1

		print(f'select_num：{select_num}')
		print(f'current_num：{current_num}')

		# 進捗(%)を計算
		# select_numから割合を算出してmath.floorで小数点以下切り捨て
		progress=math.floor(current_num/select_num*100)
		print(f'進捗：{progress}%')

		# ajaxに返すjsonレスポンス
		json_resp={'select_num':select_num, # formで選択した数値
		           'current_num':current_num, # 現在値
		           'next_num':current_num+1, # 次の数値
		           'progress':progress, # 進捗(%)
		           }

		# formで選択した数値と現在値を比較して、json_resp辞書にkey→'state'、value→状態を追加
		if select_num==current_num:
			json_resp['state']='終了'
		else:
			json_resp['state']='実行中'

		print(f'json_resp：{json_resp}')

		# 処理はほぼ一瞬で終了してしまうためスリープ
		time.sleep(1)

	return JsonResponse(json_resp)


# help_modalページの表示
def help_modal(request):
	# ログインの確認
	if request.user.is_authenticated:
		return render(request,'applications/help_modal.html')
	else:
		# ログインしていない場合はログインページへ移動
		return HttpResponseRedirect('/accounts/login/')

templates/applications/dl_csv_zip.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
<html>
	<body>

    <form id="dl_csv_zip_form" action="{% url 'app_urls:dl_csv_zip_proc' %}" method="POST">
			{% csrf_token %}

			<h4>ブログ記事「<a rel="noopener" href="https://blog.dev-neko.com/django-csv-zip" target="_blank">【Django】複数の辞書型リストをcsvに変換し、zipで圧縮してダウンロードする方法</a>」の動作確認ページです。</h4>

			<!-- textarea群 -->
			<div class="form-group">
				<h5>辞書型リスト 1つ目</h5>
				<textarea name="1つ目" class="form-control" rows="2">[{'ts': 4, 'chat': 'あああ'}, {'ts': 4, 'chat': 'いいい'}, {'ts': 5, 'chat': 'えええ'}]</textarea>
				<h5>辞書型リスト 2つ目</h5>
				<textarea name="2つ目" class="form-control" rows="2">[{'ts': 12, 'chat': 'aaa'}, {'ts': 22, 'chat': 'おおお'}, {'ts': 50, 'chat': 'bbb'}]</textarea>
				<h5>辞書型リスト 3つ目</h5>
				<textarea name="3つ目" class="form-control" rows="2">[{'ts': 0, 'chat': 'ccc'}, {'ts': 11, 'chat': 'ををを'}, {'ts': 19, 'chat': 'ddd'}]</textarea>
			</div>

			<h5>指定した辞書型リストをcsvに変換してzipでダウンロード</h5>

			<!-- チェックボックス群 -->
			<div class="form-group">
				<div class="custom-control custom-checkbox">
					<input type="checkbox" class="custom-control-input" id="checkbox_1" value="1つ目" name="checkbox">
					<label class="custom-control-label" for="checkbox_1">1つ目</label>
				</div>
				<div class="custom-control custom-checkbox">
					<input type="checkbox" class="custom-control-input" id="checkbox_2" value="2つ目" name="checkbox">
					<label class="custom-control-label" for="checkbox_2">2つ目</label>
				</div>
				<div class="custom-control custom-checkbox">
					<input type="checkbox" class="custom-control-input" id="checkbox_3" value="3つ目" name="checkbox">
					<label class="custom-control-label" for="checkbox_3">3つ目</label>
				</div>
			</div>

			<!-- ボタン群 -->
			<div class="d-flex align-items-center">
				<div>
					<!-- 保存ボタン -->
					<div class="btn-group">
						<button onFocus="this.blur()" type="submit" class="btn btn-primary" name="action" value='save'>保存</button>
					</div>
				</div>
			</div>

		</form>


	</body>
</html>
{% endblock %}

templates/applications/help_modal.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
<html>
<body>

<h4>ブログ記事「<a rel="noopener" href="https://blog.dev-neko.com/django_help_modal" target="_blank">【Django】【Bootstrap4】部品化したモーダルをヘルプボタンで表示させる</a>」の動作確認ページです。</h4>

{% include 'help_modal/help_modal_template.html' with header='<span style="font-size:2rem;">HTMLをそのまま表示</span>' modal_id='bbb' modal_title='サンプルテキスト' include_body=False modal_body='<p>サンプルテキスト</p><p>サンプルテキスト</p><p>サンプルテキスト</p>' only %}

{% include 'help_modal/help_modal_template.html' with header='<span style="font-size:2rem;">HTMLをinclude</span>' modal_id='aaa' modal_title='サンプルテキスト' include_body=True modal_body='help_modal/help_modal_body.html' only %}

</body>
</html>
{% endblock %}

templates/applications/index.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
<html>
	<body>

	<!-- リンクカード -->
	<div class="card mb-3">
		<div class="row no-gutters bg-light position-relative">
			<div class="col-md-6 mb-md-0 p-md-4">
				<img class="card-img-top" src="{% static 'img/dl_csv_zip.png' %}" data-holder-rendered="true">
			</div>
			<div class="col-md-6 position-static p-4 pl-md-0">
				<h5 class="mt-0">ブログ記事「【Django】複数の辞書型リストをcsvに変換し、zipで圧縮してダウンロードする方法」の動作確認ページです。</h5>
				<p></p>
				<a href="{% url 'app_urls:dl_csv_zip' %}" class="stretched-link">詳細を見る</a>
			</div>
		</div>
	</div>

	<!-- リンクカード -->
	<div class="card mb-3">
		<div class="row no-gutters bg-light position-relative">
			<div class="col-md-6 mb-md-0 p-md-4">
				<img class="card-img-top" src="{% static 'img/rec_ajax.png' %}" data-holder-rendered="true">
			</div>
			<div class="col-md-6 position-static p-4 pl-md-0">
				<h5 class="mt-0">ブログ記事「【Django】Ajaxで再帰処理を行う方法」の動作確認ページです。</h5>
				<p></p>
				<a href="{% url 'app_urls:rec_ajax' %}" class="stretched-link">詳細を見る</a>
			</div>
		</div>
	</div>

	<!-- リンクカード -->
	<div class="card mb-3">
		<div class="row no-gutters bg-light position-relative">
			<div class="col-md-6 mb-md-0 p-md-4">
				<img class="card-img-top" src="{% static 'img/help_modal.png' %}" data-holder-rendered="true">
			</div>
			<div class="col-md-6 position-static p-4 pl-md-0">
				<h5 class="mt-0">ブログ記事「【Django】【Bootstrap4】部品化したモーダルをヘルプボタンで表示させる」の動作確認ページです。</h5>
				<p></p>
				<a href="{% url 'app_urls:help_modal' %}" class="stretched-link">詳細を見る</a>
			</div>
		</div>
	</div>


	</body>
</html>
{% endblock %}

templates/applications/rec_ajax.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
<html>
<body>

<!-- ajax処理を行うフォーム -->
<!-- action先はDjangoテンプレートで「applications/urls.py」の「app_name」と「path」の「name」を使用して指定 -->
<form id="ajax_form" action="{% url 'app_urls:rec_ajax_proc' %}" method="POST">
	{% csrf_token %}

	<h4>ブログ記事「<a rel="noopener" href="https://blog.dev-neko.com/django-recursive-ajax" target="_blank">【Django】Ajaxで再帰処理を行う方法</a>」の動作確認ページです。</h4>

	<h5>数値の選択</h5>
	<div class="form-group">
		<select class="form-control" id="select_num">
			<option>10</option>
			<option>20</option>
			<option>30</option>
		</select>
	</div>

	<!-- ボタン群 -->
	<div class="d-flex align-items-center">
		<div>
			<!-- 実行ボタン -->
			<div class="btn-group">
				<!-- 「onFocus="this.blur()"」でボタンのフォーカス線を削除 -->
				<button onFocus="this.blur()" type="submit" class="btn btn-primary" id="run_btn">実行</button>
			</div>
			<!-- 中止ボタン -->
			<div class="btn-group">
				<!-- 「onFocus="this.blur()"」でボタンのフォーカス線を削除 -->
				<!-- 「onclick」でページをリロードさせる -->
				<input type="button" onFocus="this.blur()" class="btn btn-danger" value="中止" onclick="window.location.reload();">
			</div>
		</div>
	</div>

</form>

<!-- 現在値・状態・進捗をテーブルで表示 -->
<h5>結果表示テーブル</h5>
<table class="table table-bordered">
	<thead>
	<tr>
		<th style="width:15%">現在値</th>
		<th style="width:15%">状態</th>
		<th>進捗</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<!-- 現在値のセル -->
		<td id="current_num_cell"><br></td>
		<!-- 状態のセル -->
		<td id="state_cell"><br></td>
		<!-- 進捗のセル -->
		<td id="progress_cell">
			<!-- プログレスバーの初期表示 -->
			<div class="progress">
				<div class="progress-bar progress-bar-striped progress-bar-animated"
						 style="width:0%"
						 role="progressbar"
						 aria-valuenow="0"
						 aria-valuemin="0"
						 aria-valuemax="100">0%</div>
			</div>
		</td>
	</tr>
	</tbody>
</table>

</body>
</html>
{% endblock %}

templates/base/base.html
{% load static %}
<html lang="ja">
	<head>
		<!-- head ここから -->
		{% include 'base/head.html' %}
		<!-- head ここまで -->
	</head>
	<body>
		<!-- navbar ここから -->
		{% include "base/navbar.html" %}
		<!-- navbar ここまで -->

		<!-- content ここから -->
		<!-- ナビバー以外に余白を入れるために指定 -->
		<div class="between-content">
			{% block content %}
			{% endblock %}
		</div>
		<!-- content ここまで -->

		<!-- 外部jsファイル ここから -->
		{% include "base/js.html" %}
		<!-- 外部jsファイル ここまで -->

		<!-- Footer ここから -->
		{% include "base/footer.html" %}
		<!-- Footer ここまで -->
	</body>
</html>

templates/base/footer.html
{% load static %}
<link href="{% static 'css/footer.css' %}" rel="stylesheet">

<footer class="footer">
	<div class="container">
		<div class="row">

			<!-- ヘッダー以外のリンク -->
			<div class="col-xl">
				<ul class="list-inline">
					<li class="list-inline-item"><a href="javascript:void(0)">サンプルリンク</a></li>
					<li class="list-inline-item"><a href="javascript:void(0)">サンプルリンク</a></li>
					<li class="list-inline-item"><a href="javascript:void(0)">サンプルリンク</a></li>
				</ul>
			</div>

			<!-- テキスト表示 -->
			<div class="col-xl">
				<p class="support-parts-desc">
					サンプルテキスト<br>サンプルテキスト<br>サンプルテキスト
				</p>
			</div>

		</div>

		<!-- コピーライト -->
		<div class="border-hr"></div>
		<div class="text-center">
			<a style="color: #fff;">Copyright © サイト名 {% now "Y" %}</a>
		</div>

	</div>
</footer>

templates/base/head.html
{% load static %}
<title>{% include "base/title.html" %}</title>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- デフォルトのcss -->
<link href="{% static 'css/default.css' %}" rel="stylesheet">
<!-- font-awesome/4.1.0 -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
<!-- jquery-3.4.1.min.js -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<!-- bootstrap@4.5.3 4.5系最終版 -->
<!-- https://getbootstrap.com/docs/4.5/getting-started/introduction/ -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<!-- bootstrapのcssを上書きするcss -->
<link href="{% static 'css/bootstrap_override.css' %}" rel="stylesheet">

templates/base/js.html
{% load static %}
<!-- ajax処理のために読み込み -->
<script type="text/javascript" src="{% static 'js/rec_ajax.js' %}"></script>

templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark mb-4" style="background-color:#000000;">
	<a class="navbar-brand" href="{% url 'app_urls:index' %}">{% include "base/title.html" %}</a>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
	<ul class="navbar-nav">
		</li>
		<li class="nav-item">
			<a class="nav-link active" href="{% url 'admin:index' %}">admin</a>
		</li>
		<li class="nav-item">
			<a class="nav-link active" href="{% url 'logout' %}">ログアウト</a>
	</ul>
	</div>
</nav>

templates/base/popover_headline_v1.html
<div class="d-flex align-items-center">
	{{ title }}
	<button type="button" class="btn btn-dark rounded-circle p-0 d-flex align-items-center  justify-content-center"
					style="width:1.3rem;height:1.3rem;position:relative;left:3px;position:relative;top:-4px;"
					data-trigger="focus"
					data-placement="right"
					data-toggle="popover"
					data-html="true"
					data-content="{{ description }}">？
	</button>
</div>

templates/base/title.html
タイトル

templates/frontpage.html
<!DOCTYPE html>
{% load widget_tweaks %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>
<body>
    <nav class="navbar has-background-warning">
        <div class="navbar-brand">
          <a href="/" class="navbar-item">
            <strong>sasasaの求人スクレイピングサイト</strong>
          </a>
        </div>
    </nav>
    <div style="padding: 150px 300px;">
        <form action="" method="post">
            {% csrf_token %}
            <h2 class="is-size-3">サイトを選択</h2>
            <div class="has-text-centered">
                <div class="select has-text-centered">
                    {% for field in siteform %}
                    {{field}}
                    {% endfor %}
                </div>
            </div>
            <h2 class="is-size-3">件数</h2>
            {% render_field form.count class+="input has-text-centered" %}
            <h2 class="is-size-3">職種</h2>
            {% render_field form.occupation class+="input has-text-centered" %}
            <div class="has-text-centered">
                <input type="submit" value="取得" class="button has-background-danger has-text-white is-medium" style="margin: 50px;">
            </div>
        </form>
        <div class="has-text-centered is-size-5" style="color: red; font-weight: bold;">
            {{conclusion}}
        </div>
        <div style="color: blue;">
            {{item_info}}
        </div>
    </div>
</body>
</html>

templates/help_modal/help_modal_body.html
{% load static %}
<p>
	サンプルテキスト
</p>
<p align="center">
	<img src="{% static 'img/sample_image.png' %}">
</p>
<p>
	サンプルテキスト
</p>
<p>
	<a href="{% url 'app_urls:rec_ajax' %}" target="_blank"><u>ブログ記事「【Django】Ajaxで再帰処理を行う方法」の動作確認ページです。</u></a>
</p>

templates/help_modal/help_modal_template.html
<div class="d-flex align-items-center">
	{{ header }}
	<button type="button"
					class="btn btn-dark rounded-circle p-0 d-flex align-items-center justify-content-center"
					style="width:1.3rem; height:1.3rem; position:relative; left:3px; position:relative;"
					data-toggle="modal"
					data-target="#{{ modal_id }}"
					title="ヘルプ">?
	</button>
</div>
<div class="modal fade"
		 id="{{ modal_id }}"
		 tabindex="-1"
		 role="dialog"
		 aria-labelledby="{{ modal_id }}_label1"
		 aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="{{ modal_id }}_label2">{{ modal_title }}</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				{# include_bodyの内容でincludeするかそのまま表示させるか分岐 #}
				{% if include_body %}
					{% include modal_body %}
				{% else %}
					{{ modal_body }}
				{% endif %}
			</div>
		</div>
	</div>
</div>